default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: uni_connect_development

test:
  <<: *default
  database: uni_connect_test

production:
  <<: *default
  database: uni_connect_production
  username: uni_connect
  password: <%= ENV["UNI_CONNECT_DATABASE_PASSWORD"] %>
